import type { Metadata } from "next";
import "./reset.css";
import "./globals.css";
import MainHeader from "./components/mainHeader/mainHeader";
import { AntdRegistry } from "@ant-design/nextjs-registry";

export const metadata: Metadata = {
  title: "Parking",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AntdRegistry>
          <MainHeader />
          {children}
        </AntdRegistry>
      </body>
    </html>
  );
}
